title: Jonathan Michaux
description: Robotics, AI, biology
url: https://jonmichaux.com

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

permalink: /blog/:year/:month/:day/:title/
theme: null
